export const countries = [
  "Afghanistan",
  "Angola",
  "Albania",
  "United Arab Emirates",
  "Argentina",
  "Armenia",
  "Antarctica",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Burundi",
  "Belgium",
  "Benin",
  "Burkina Faso",
  "Bangladesh",
  "Bulgaria",
  "The Bahamas",
  "Belarus",
  "Belize",
  "Bolivia",
  "Brazil",
  "Brunei",
  "Bhutan",
  "Botswana",
  "Canada",
  "Switzerland",
  "Chile",
  "China",
  "Ivory Coast",
  "Cameroon",
  "Colombia",
  "Costa Rica",
  "Cuba",
  "Northern Cyprus",
  "Cyprus",
  "Czechia",
  "Germany",
  "Djibouti",
  "Denmark",
  "Dominican Republic",
  "Algeria",
  "Ecuador",
  "Egypt",
  "Eritrea",
  "Spain",
  "Estonia",
  "Ethiopia",
  "Finland",
  "Fiji",
  "Falkland Islands",
  "France",
  "Gabon",
  "United Kingdom",
  "Georgia",
  "Ghana",
  "Guinea",
  "Gambia",
  "Guinea Bissau",
  "Equatorial Guinea",
  "Greece",
  "Greenland",
  "Guatemala",
  "Guyana",
  "Honduras",
  "Croatia",
  "Haiti",
  "Hungary",
  "Indonesia",
  "India",
  "Ireland",
  "Iran",
  "Iraq",
  "Iceland",
  "Israel",
  "Italy",
  "Jamaica",
  "Jordan",
  "Japan",
  "Kazakhstan",
  "Kenya",
  "Kyrgyzstan",
  "Cambodia",
  "South Korea",
  "Kosovo",
  "Kuwait",
  "Laos",
  "Lebanon",
  "Liberia",
  "Libya",
  "Sri Lanka",
  "Lesotho",
  "Lithuania",
  "Luxembourg",
  "Latvia",
  "Morocco",
  "Moldova",
  "Madagascar",
  "Mexico",
  "North Macedonia",
  "Mali",
  "Myanmar",
  "Montenegro",
  "Mongolia",
  "Mozambique",
  "Mauritania",
  "Malawi",
  "Malaysia",
  "Namibia",
  "New Caledonia",
  "Niger",
  "Nigeria",
  "Nicaragua",
  "Netherlands",
  "Norway",
  "Nepal",
  "New Zealand",
  "Oman",
  "Pakistan",
  "Panama",
  "Peru",
  "Philippines",
  "Papua New Guinea",
  "Poland",
  "Puerto Rico",
  "North Korea",
  "Portugal",
  "Paraguay",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Western Sahara",
  "Saudi Arabia",
  "Sudan",
  "South Sudan",
  "Senegal",
  "Solomon Islands",
  "Sierra Leone",
  "El Salvador",
  "Somaliland",
  "Somalia",
  "Serbia",
  "Suriname",
  "Slovakia",
  "Slovenia",
  "Sweden",
  "Eswatini",
  "Syria",
  "Chad",
  "Togo",
  "Thailand",
  "Tajikistan",
  "Turkmenistan",
  "Timor Leste",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Taiwan",
  "Tanzania",
  "Uganda",
  "Ukraine",
  "Uruguay",
  "United States of America",
  "Uzbekistan",
  "Venezuela",
  "Vietnam",
  "Vanuatu",
  "West Bank",
  "Yemen",
  "South Africa",
  "Zambia",
  "Zimbabwe",
].sort((a, b) => a.localeCompare(b));
